@baseUrl = http://localhost:3001/api
@channel = something

############################################################

###
# @name getAll
GET {{baseUrl}} HTTP/1.1

###
# @name getChannel
GET {{baseUrl}}/channel/{{channel}} HTTP/1.1

###
# @name updateChannel
POST {{baseUrl}}/channel/{{channel}} HTTP/1.1

###
# @name saveChannel
POST {{baseUrl}}/channel HTTP/1.1
Content-Type: application/json

{
  "path": "{{getChannel.response.body.path}}",
  "title": "{{getChannel.response.body.title}}",
  "category": "{{getChannel.response.body.category}}",
  "extra": "field"
}

###
# @name deleteChannel
DELETE {{baseUrl}}/channel/{{channel}} HTTP/1.1